require "user.keymaps"
require "user.plugins"
require "user.autocommands"
require "user.colorscheme"
require "user.cmp"
require "user.lsp"
require "user.telescope"
require "user.treesitter"
require "user.autopairs"
require "user.comment"
require "user.gitsigns"
require "user.nvim-tree"
require "user.lualine"
require "user.toggleterm"
require "user.project"
require "user.impatient"
require "user.indentline"
require "user.whichkey"
require "user.hop"
require "user.numb"
-- require "user.colorizer"
require "user.todo-comments"
require "user.illuminate"
require "user.lir"
-- require "user.cybu"
require "user.options"
require "user.nvim-webdev-icons"
require "user.dressing"
require "user.tabout"
require "user.fidget"
-- require "user.browse"
require "user.auto-session"
require "user.surround"
